title: Mechanical Engineering Portfolio
description: Cal Poly Pomona Formula SAE — Clutch & Shifter Captain | Mechanical Engineering Student
theme: jekyll-theme-minimal
url: https://dtcarwall-code.github.io
baseurl: /Mechanical_Engineering_Portfolio
repository: dtcarwall-code/Mechanical_Engineering_Portfolio
show_downloads: false
